export const SIGN_UP_STARTED = "SIGN_UP_STARTED";
export const SIGN_UP_SUCCEEDED = "SIGN_UP_SUCCEEDED";
export const SIGN_UP_FAILED = "SIGN_UP_FAILED";
export const SIGN_UP_SHOW_ERROR_MESSAGE = "SIGN_UP_SHOW_ERROR_MESSAGE";
export const SIGN_UP_CLEAR_ERROR_MESSAGE = "SIGN_UP_CLEAR_ERROR_MESSAGE";
export const SIGN_UP_RESET_STATE = "SIGN_IN_RESET_STATE";
