export const SIGN_IN_STARTED = "SIGN_IN_STARTED";
export const SIGN_IN_SUCCEEDED = "SIGN_IN_SUCCEEDED";
export const SIGN_IN_FAILED = "SIGN_IN_FAILED";
export const SIGN_IN_SHOW_ERROR_MESSAGE = "SIGN_IN_SHOW_ERROR_MESSAGE";
export const SIGN_IN_CLEAR_ERROR_MESSAGE = "SIGN_IN_CLEAR_ERROR_MESSAGE";
export const SIGN_IN_RESET_STATE = "SIGN_IN_RESET_STATE";
