export const DEVICES_RESET_STATE = "DEVICES_RESET_STATE";
export const DEVICES_FETCH_SUCCEEDED = "DEVICES_FETCH_SUCCEEDED";
export const DEVICES_CHANGE_FILTER_VALUE = "DEVICES_CHANGE_FILTER_VALUE";
export const DEVICES_START_EDIT = "DEVICES_START_EDIT";
export const DEVICES_END_EDIT = "DEVICES_END_EDIT";
export const DEVICES_CREATE_SUCCEEDED = "DEVICES_CREATE_SUCCEEDED";
export const DEVICES_EDIT_SUCCEEDED = "DEVICES_EDIT_SUCCEEDED";
export const DEVICES_DELETE_SUCCEEDED = "DEVICES_DELETE_SUCCEEDED";
