export const LOCATIONS_RESET_STATE = "LOCATIONS_RESET_STATE";
export const LOCATIONS_FETCH_SUCCEEDED = "LOCATIONS_FETCH_SUCCEEDED";
export const LOCATIONS_CHANGE_FILTER_VALUE = "LOCATIONS_CHANGE_FILTER_VALUE";
export const LOCATIONS_CREATE_SUCCEEDED = "LOCATIONS_CREATE_SUCCEEDED";
